main: com.mengcraft.server.AntiCraft
name: AntiCraft
version: 0.1.1
website: http://www.mengcraft.com/

commands:
  craft:
    description: Basic command of this plugin.
    permission: craft.admin

permissions:
  craft.admin:
    description: Admin permission of this plugin.
    default: op