main: com.mengcraft.server.LoginTeleport
name: LoginTeleport
version: 0.2.1
website: http://www.mengcraft.com/

commands:
  login-tp:
    description: Basic command.
    permission: server.admin

permissions:
  server.admin:
    description: Basic permission.
    default: op