main: com.mengcraft.server.AntiAnvil
name: AntiAnvil
version: 0.1.1
website: http://www.mengcraft.com/

permissions:
  anvil.use:
    description: Basic plugin permission.
    default: op
  enchanting.use:
    description: Allow enchanting.
    default: op