name: BanWorld
main: com.mengcraft.server.BanWorld
version: 0.3.0

commands:
  bw:
    description: Basic command of this plugin.
    permission: worlds.admin

permissions:
  bw.admin:
    description: Basic permission of this plugin.
    default: true